### ISSUE TITLE
Apparently Lao\Lao.unicharset Has Uncommitted Changes

### ISSUE THREAD

**Issue by ColdWinterWind** [tesseract-ocr/langdata_lstm#17]
I've just installed Git Desktop on Win10 and started cloning Tesseract-ocr.  When the process finished the desktop showed that the above-referenced file had been changed, sh...owed the changed lines 

>-163
NULL 0 NULL 0
Joined 0 0,255,0,255,0,0,0,0,0,0 NULL 0 0 0 	# Joined [4a 6f 69 6e 65 64 ]
|Broken|0|1 0 0,255,0,255,0,0,0,0,0,0 NULL 0 0 0 	# Broken
85
NULL 0 Common 0
Joined 7 0,255,0,255,0,0,0,0,0,0 Latin 1 0 1 Joined	# Joined [4a 6f 69 6e 65 64 ]a
|Broken|0|1 f 0,255,0,255,0,0,0,0,0,0 Common 2 10 2 |Broken|0|1	# Broken
...
and many, many more

Further, the desktop offered me the opportunity to Commit the changes.

It appears that lines 1-4 have been changed, and many lines have been added; but since it's not my code, far be it from me to actually commit the changes.

May I ask for any recommendations?
TIA

**Comment by zdenop** [comment]
Please use tesseract user forum for asking questions/support.
