### ISSUE TITLE
Alternative way to download langdata_lstm master file instead from github

### ISSUE THREAD

**Issue by timjin520** [tesseract-ocr/langdata_lstm#38]
I'm trying to download the langdata_lstm from a work laptop. However, I couldnt download this file in github due to a firewall block which i have no control on. Is there another site that i can download this file from? 

thank you

**Comment by stweil** [comment]
Does your firewall block GitHub, or what exactly is blocked?

**Comment by timjin520** [comment]
Thank you for your reply. Our firewall blocks anything that download from
github. Only file I want to get is langdata_lsmt master zip file which I
couldn't find outside of github.

**Comment by stweil** [comment]
If only downloads are blocked, `git clone` should work and would also get the desired files.

**Comment by timjin520** [comment]
Sorry, that also blocks that. Is there a other site where I can download it?

**Comment by stweil** [comment]
But you are able to write here, so you have access to https://github.com/. Then why does `git clone` not work?

**Comment by timjin520** [comment]
I do and im able to access and view github. Sorry I work at a federal
building. Their restrictions are little high. They have a firewall that
blocks an outgoing connections when I use github app, python, maven, etc.
will not work if I do cloning or download files from github. And cannot use
external hd on federal machines. So I cannot modify the restrictions. Only
thing I would need for my project is the langdata master zip. I want to
know if theres any other site that have that zip file outside of github. I
can't find it on google.

FYI, I cannot login gmail on my work machine (using my phone). So a
download link that is not github would be helpful. Hopefully it works.

Thank you

**Comment by zdenop** [comment]
As far as we know these data are not available anywhere else.
IMO you try to solve problem on wrong end: if you need these data on your work computer, you have to cooperate with your IT support to make it available for you. 
Downloading&using data/programs from not official source is security risks.

**Comment by stweil** [comment]
@timjin520, you might try https://code.bib.uni-mannheim.de/UB-Mannheim/langdata_lstm.

**Comment by timjin520** [comment]
Thank you so much!!! I got it downloaded. Thank you so much for your help!

**Comment by tfmorris** [comment]
@stweil Sounds like this is resolved/answered.

**Comment by stweil** [comment]
Yes, I think so, too, and closed this issue.
