### ISSUE TITLE
Armenian.traineddata contains the missing character, so I suggest to try that model.

### ISSUE THREAD

**Issue by reneclais** [tesseract-ocr/langdata_lstm#50]
Armenian.traineddata contains the missing character, so I suggest to try that model.

_Originally posted by @stweil in https://github.com/tesseract-ocr/langdata_lstm/issues/49#issuecomment-1729729956_

**Comment by reneclais** [comment]
I use this model with pleasure if I can find it, where is this model located ?

**Comment by stweil** [comment]
Please don't open new issues for simple questions. There is a Tesseract user forum.
