### ISSUE TITLE
Armenian letter և missing in hye language -  confirmation

### ISSUE THREAD

**Issue by reneclais** [tesseract-ocr/langdata_lstm#51]
I checked the armenian hye.training_text and hye.wordlist  and I confirm that the և sign is not included in those files.   The  և  sign  is replaced by the   եւ   sign,    they have both the same meaning   but  in armenian the   printed document  will use the և sign and not not the եւ   sign  .

**Comment by stweil** [comment]
Please don't open new issues for things which are already discussed in another issue.
