### ISSUE TITLE
Adding additional language Denjongke (sikkimese bhutia) to tesseract language dataset

### ISSUE THREAD

**Issue by bloodgroup-cplusplus** [tesseract-ocr/langdata_lstm#52]
We are currently trying to add Sikkimese bhutia language for ocr language engine. The letters and words are similar to Dzongkha (dzo) language which is already present in the current dataset . However there are additional letters and words which are not included in Dzongkha dataset. How can we contribute ?

**Comment by stweil** [comment]
Please note that newer models and language support should no longer use langdata, but langdata_lstm. I therefore transferred this issue to that repository.

You can contribute a new language or script by sending a pull request for langdata_lstm. Use an existing language as a template for your contribution.

**Comment by bloodgroup-cplusplus** [comment]
Thanks a lot @stweil .. will do as suggested..

**Comment by amitdo** [comment]
If you want to have a new model, you have to train it yourself. Contributing the dataset does not mean that someone else will do the work for you.
